# Generated by Django 5.0 on 2024-01-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.TextField()),
                ('dish_description', models.TextField(null=True)),
                ('dish_type', models.TextField()),
                ('dish_calories', models.IntegerField(null=True)),
                ('light_healthy', models.BooleanField(null=True)),
                ('sugar_free', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='DishDate',
            fields=[
                ('date_saved', models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'date_saved',
            },
        ),
        migrations.CreateModel(
            name='DateHasDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('dish_id', models.ForeignKey(db_column='dish_id', on_delete=django.db.models.deletion.CASCADE, to='common.dish')),
                ('date', models.ForeignKey(db_column='date', on_delete=django.db.models.deletion.CASCADE, to='common.dishdate')),
            ],
            options={
                'db_table': 'date_has_dish',
            },
        ),
    ]
