# Generated by Django 5.0 on 2024-01-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_date_datehasdish_dish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datehasdish',
            name='id',
        ),
        migrations.AddField(
            model_name='datehasdish',
            name='date_has_dish_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
