# Generated by Django 5.0 on 2024-02-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_datehasdish_id_datehasdish_date_has_dish_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishdate',
            name='attendance',
            field=models.IntegerField(null=True),
        ),
    ]
