# Generated by Django 5.0 on 2024-02-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_dishdate_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishDate',
            new_name='DateSaved',
        ),
        migrations.RenameField(
            model_name='datesaved',
            old_name='date_saved',
            new_name='date_saved',
        ),
        migrations.AlterModelTable(
            name='datesaved',
            table='date_saved',
        ),
    ]
