# Generated by Django 5.0 on 2025-05-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_rename_dishdate_datesaved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datehasdish',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datehasdish',
            name='rating_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
