# Generated by Django 5.0 on 2024-01-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='date',
            table='date',
        ),
        migrations.AlterModelTable(
            name='datehasdish',
            table='date_has_dish',
        ),
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
