# Generated by Django 5.0 on 2024-01-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0002_alter_date_table_alter_datehasdish_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datehasdish',
            name='date',
            field=models.ForeignKey(db_column='date', on_delete=django.db.models.deletion.CASCADE, to='chef_management.date'),
        ),
        migrations.AlterField(
            model_name='datehasdish',
            name='dish_id',
            field=models.ForeignKey(db_column='dish_id', on_delete=django.db.models.deletion.CASCADE, to='chef_management.dish'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='dish_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
