# Generated by Django 5.0 on 2024-01-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0003_alter_datehasdish_date_alter_datehasdish_dish_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='dish2',
        ),
    ]
