# Generated by Django 5.0 on 2024-01-22 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0004_alter_dish_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dish',
            table='dish',
        ),
    ]
