# Generated by Django 5.0 on 2024-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0005_alter_dish_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='datehasdish',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
