# Generated by Django 5.0 on 2024-01-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0006_datehasdish_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='calories',
            new_name='dish_calories',
        ),
    ]
