# Generated by Django 5.0 on 2024-01-26 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0007_rename_calories_dish_dish_calories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='DishDate',
        ),
        migrations.AlterModelTable(
            name='dishdate',
            table='date_saved',
        ),
    ]
