# Generated by Django 5.0 on 2024-01-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0008_rename_date_dishdate_alter_dishdate_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishdate',
            old_name='date',
            new_name='date_saved',
        ),
    ]
