# Generated by Django 5.0 on 2024-01-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_management', '0009_rename_date_dishdate_dish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datehasdish',
            name='date',
        ),
        migrations.RemoveField(
            model_name='datehasdish',
            name='dish_id',
        ),
        migrations.DeleteModel(
            name='DishDate',
        ),
        migrations.DeleteModel(
            name='DateHasDish',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
